global using System;
global using NUnit.Framework;
global using OpenQA.Selenium;
global using OpenQA.Selenium.Edge;
global using OpenQA.Selenium.Firefox;
global using OpenQA.Selenium.Chrome;
global using OpenQA.Selenium.Internal;
global using OpenQA.Selenium.Support.UI;
global using OpenQA.Selenium.Support.Extensions;